on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'version to deploy (ingored)'  
name: deploy to demo.pnmt.portup.io from registry

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /opt/pnmt.webapp/
          sudo docker-compose stop
          sudo docker-compose rm -f
          sudo docker-compose pull   
          sudo docker-compose up -d
          cd /opt/pnmtd
          sudo docker-compose stop
          sudo docker-compose rm -f
          sudo docker-compose pull   
          sudo docker-compose up -d
