# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository: muqiuq/PNMT.WebApp
        path: PNMT.WebApp
    - uses: actions/checkout@v3
      with:
        repository: muqiuq/PNMTD
        path: PNMTD
        ssh-key : '${{ secrets.PRIVATE_SSH_KEY }}'
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      working-directory: PNMT.WebApp
      run: dotnet restore
    - name: Build
      working-directory: PNMT.WebApp
      run: dotnet build --no-restore
    - name: Test
      working-directory: PNMT.WebApp
      run: dotnet test --no-build --verbosity normal
